var Wall = Java.type("engine.entities.Wall");
var C = Java.type("components.Constants");

manager.spawn(new Wall(-C.BORDER_WALL_THICKNESS, -C.BORDER_WALL_THICKNESS, C.BORDER_WALL_THICKNESS, C.WORLD_HEIGHT + 2 * C.BORDER_WALL_THICKNESS));
manager.spawn(new Wall(0, -C.BORDER_WALL_THICKNESS, C.WORLD_WIDTH, C.BORDER_WALL_THICKNESS));
manager.spawn(new Wall(0, C.WORLD_HEIGHT, C.WORLD_WIDTH, C.BORDER_WALL_THICKNESS));
manager.spawn(new Wall(C.WORLD_WIDTH, -C.BORDER_WALL_THICKNESS, C.BORDER_WALL_THICKNESS, C.WORLD_HEIGHT + 2 * C.BORDER_WALL_THICKNESS));